### ISSUE TITLE
New sequence

### ISSUE THREAD

**Issue by bookdude13** [ProtonLights/cli#16]
Implement the new-sequence command

**Comment by bookdude13** [comment]
Should sequence data (music file, sections) be in a folder specific to the sequence?
E.g. if there was a sequence named "Dissonance", would Dissonance.ogg and dissonance_section1 go in the folder Dissonance/ ?

**Comment by rjayatilleka** [comment]
Makes sense to me.

**Comment by bookdude13** [comment]
Closed via #18.
