### ISSUE TITLE
User permissions

### ISSUE THREAD

**Issue by bookdude13** [ProtonLights/cli#24]
Create a way to store, add, and remove user permissions. Should be used on another user, granting them the specified permission. Command could be of the form `(allow|deny) <user-id> <permission> <target> <private-key> `, with target being the 'thing' the permission is applied to (project, sequence, sequence section) and private-key being the private key of the current user (to check if they can in fact grant the permission).

List of permissions:
- Granting permissions
- Editing project metadata
- Editing sequence (song, sectioning, etc.)
- Editing sequence section

**Comment by bookdude13** [comment]
To make this work, I'm thinking of creating an admin account during the creation of a new project, with that account's public key given to the init command. That way there will be at least one user with the GrantPerm permission, who can then delegate more admins as necessary. Most commands will also have to have a private key argument associated with them so that the user's permissions can be looked up and checked for that command. Thoughts?

**Comment by rjayatilleka** [comment]
Makes sense to me.

**Comment by bookdude13** [comment]
Closed by #27. Woo!
