### ISSUE TITLE
Argument parsing

### ISSUE THREAD

**Issue by bookdude13** [ProtonLights/cli#4]
Maybe use argparse to handle cli arguments?
https://github.com/tailhook/rust-argparse

**Comment by bookdude13** [comment]
Or docopt or getopts?
https://github.com/docopt/docopt.rs
https://doc.rust-lang.org/getopts/getopts/index.html

**Comment by rjayatilleka** [comment]
I was definitely going to use docopt. I like that approach a lot better than argparse. I'm going to be working on the website mostly this week while I'm at home, so if you want to go ahead and work on this, that's great.

**Comment by bookdude13** [comment]
Closed by #7.
