### ISSUE TITLE
Identify user

### ISSUE THREAD

**Issue by bookdude13** [ProtonLights/cli#8]
Implement `user id <private>` command.

**Comment by bookdude13** [comment]
I'm having trouble finding a library to get a RSA public key from a private key. @rjayatilleka if you have time, could you look into this as well? I might just be missing something obvious.

**Comment by rjayatilleka** [comment]
I think [openssl](http://sfackler.github.io/rust-openssl/doc/v0.7.13/openssl/index.html) or [openssl-sys](http://sfackler.github.io/rust-openssl/doc/v0.7.13/openssl_sys/) (for raw C bindings) are what you want.

In the `openssl` docs, I think this method is your best bet: [`fn private_key_from_pem<R>(reader: &mut R) -> Result<RSA, SslError>`](http://sfackler.github.io/rust-openssl/doc/v0.7.13/openssl/crypto/rsa/struct.RSA.html#method.private_key_from_pem).

**Comment by bookdude13** [comment]
Closed with #15.
